
CONTEND_ONLY_JSON = "The service only accept json data"
CONTEND_ONLY_ONE_JSON = "This method only accept one json, not list"
CONTEND_ARRAY_JSON = "Empty json"
CONTEND_DB_STOPED_SERVICE = "The database service is not available"
CONTEND_BAD_PASS = "Incorrect password"
CONTEND_DB_ERROR_SERVICE = "The database service has had an internal error."
CONTEND_DIFERENT_USER = "Diferent usernames in json array"
CONTEND_BAD_FIELD = "Bad number, name and/or format of the some field"
CONTEND_BAD_REGEX = "Bad format the content of the some field"
CONTEND_USER_EXIST = "The user already exists: {}"
CONTEND_USER_CREATE = "Success in creating the user: {}"
CONTEND_BAD_USER = "The user not exist: {}"
CONTEND_NO_ALLOWED_LIST = "Lists or arrays not allowed in registration"
CONTEND_INSERTED_DEVICE = "Success in inserting the device mesurement(s)"
CONTEND_INSERTED_WEATHER = "Success in inserting the weather mesurement(s)"
CONTEND_INSERTED_SURVEY = "Success in inserting the survey(s)"